export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  CONTACTS: '/contacts',
  CONTACT_PROFILE: '/contacts/profile/:id',
  SOCIAL: '/social',
  SOCIAL_NEW_POST: '/social/new-post',
  MARKETPLACE: '/marketplace',
  PRODUCT: '/marketplace/product/:id',
  ANALYTICS: '/analytics',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_EDDM: '/admin/eddm',
  PROFILE: '/profile',
  PROFILE_CART: '/profile/cart',
  PROFILE_BILLING: '/profile/billing',
  PROFILE_SETTINGS: '/profile/settings',
  PROFILE_NOTIFICATIONS: '/profile/notifications',
  PROFILE_SECURITY: '/profile/security',
  EMAIL_MARKETING: '/email-marketing',
  EMAIL_TEMPLATE_CREATOR: '/email-marketing/template/create',
  NEW_CAMPAIGN: '/email-marketing/campaign/new',
  AD_PORTAL: '/ad-portal',
  LEADS: '/leads'
} as const;